---
title: "Change of Evidence Vignette t-Test"
author: "Moritz C. Dechamps"
date: "19 7 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Generate Sample Data

```{r}
df <- data.frame(exp=rbinom(100,20,0.55), con=rbinom(100,20,0.5))
summary(df)
```

## Load library

```{r}
library(changeofevidence)
```

## Calculate Sequential Bayes Factors

```{r}
# Undirectional one-sample t-tests with broad prior
bf.exp <- bfttest(df$exp, mu = 10, alternative = "two.sided", prior.loc = 0, prior.r = 0.707)
bf.con <- bfttest(df$con, mu = 10, alternative = "two.sided", prior.loc = 0, prior.r = 0.707)

# Directional paired samples t-test with narrow prior
bf.paired <- bfttest(df$exp, df$con, alternative = "greater", paired = T, prior.loc = 0, prior.r = 0.1)

# Append data to df
df$bf.exp <- bf.exp$BF
df$bf.con <- bf.con$BF
df$bf.paired <- bf.paired$BF
```

## Plot Seq BFs

```{r, echo=FALSE}
# Plot single BF
plotbf(df$bf.paired)

# Plot multiple BFs
plotbf(list(exp=df$bf.exp, con=df$bf.con))
```

## Create simulations

```{r, echo=FALSE}
# Indicate the amount of trials of one experimental run (e.g. 100 subjects * 20 trials)
# Specify the same test parameters as the test(s) you want to compare to (in this case the one-sample t-tests.)
sims <- simcreate(100*20, n.sims = 100, mean.scores = 10, use.files = F, alternative = "two.sided", prior.loc = 0, prior.r = 0.707)
```

## Plot BFs with simulation data

```{r, echo=FALSE}
plotbf(list(exp=df$bf.exp, con=df$bf.con), sims.df = sims)
```

## CoE 1: Maximum BF

```{r}
r.exp.maxbf <- maxbf(df$bf.exp, sims.df = sims)
r.con.maxbf <- maxbf(df$bf.con, sims.df = sims)
```

## CoE 2: BF Energy

```{r}
r.exp.nrg <- energybf(df$bf.exp, sims.df = sims)
r.con.nrg <- energybf(df$bf.con, sims.df = sims)
```

## Coe 3: FFT Amplitude Sum

```{r}
# Create Fast Fourier Transforms of Sequential BFs
fft <- data.frame(exp=fftcreate(bf.exp$BF), con=fftcreate(bf.con$BF))

# Compare amplitude sums with simulations
r.exp.fft <- ffttest(fft$exp, sims.df = sims)
r.con.fft <- ffttest(fft$con, sims.df = sims)

# Plot FFTs
# Use parameter "coordy" to ensure a comparable coordinate system
plotfft(fft$exp, sims.df = sims)
plotfft(fft$con, sims.df = sims)
```

