# Create Simulations
#' Generate simulations for comparison
#'
#' This function generates a dataframe containing multiple simulations of random data.
#'
#' The tests of this package rely on comparisons of the experimental data to simulated random data sets.
#' This function can provide a dataframe containing multiple simulated runs of the experiment with completely random data.
#' To generate the random data a software-based pseudo-RNG can be used or - better - the package provides text-files containing random bit sequences previously generated by a quantum-based trueRNG (Quantis).
#' Simulations can be created for binomial datasets and bits can be summed up to represent normally distributed mean scores.
#'
#' @param trials The amount of trials in a single experiment (this includes all subjects).
#' @param n.sims The amount of simulations to be generated. 10,000 is recommended, this might take several hours or days, though, depending on the sample size and number of trials.
#' @param mean.scores Should bits be summed up to represent a normal distribution centered about a mean? If yes, indicate the desired mean score here. If you are comparing to binomial data, set to NULL.
#' @param method The method used to generate the random data. Options are "pseudo" (software-based pseudo-RNG), "files" (text-files containing random bit sequences) and "quantis" (trueRNG device). Default is "pseudo".
#' @param filespath If random files should be used indicate the path to those files.
#' @param parallel If set to TRUE, multiple cores are being used in parallel to generate the simulations (recommenden).
#' @param nstart Number of data points that are considered before calculating the first BF (min = 2)
#' @param alternative Set parameter for Bayesian testing (t-Test).
#' @param prior.loc Set parameter for Bayesian testing (t-Test).
#' @param prior.r Set parameter for Bayesian testing.
#' @param p Set parameter for Bayesian testing (Binomial) or data generation for probabilities of success other than 0.5.
#' @return A dataframe with trials*nsims rows containing the columns "simid","index","rw","density.rw","bf" and "density.bf".
#' @examples
#' sims.pseudo <- simcreate(trials = 100, n.sims = 1000, method = "pseudo")
#' sims.files <- simcreate(trials = 100*20, n.sims = 1000, mean.scores = 10, method = "files", filespath = "RandomFiles/")
#' sims.quantis <- simcreate(trials = 1000, method = "quantis")
#' sims.parallel <- simcreate(trials = 376*100, n.sims = 1000, mean.scores = 50, method = "pseudo", parallel = TRUE) # 376 participants with 100 summed up trials each
#' @export

simcreate <- function(trials, n.sims = 1000, mean.scores = NULL, method = c("pseudo", "files", "quantis"), filespath = "RandomFiles/", parallel = TRUE, nstart = 5, alternative = c("two.sided", "less", "greater"), prior.loc = 0, prior.r = 0.1, p = 0.5, use.files = NULL, use.quantis = NULL) {
  
  # Backwards compatibility
  if (!is.null(use.files) && use.files == TRUE) {
    message("The argument `use.files` is deprecated. Please use `method = 'files'` instead.")
    method <- "files"
  }
  if (!is.null(use.quantis) && use.quantis == TRUE) {
    message("The argument `use.quantis` is deprecated. Please use `method = 'quantis'` instead.")
    method <- "quantis"
  }
  # Input Checks
  if (!is.numeric(trials) || trials <= 0) stop("Trials must be a positive number.")
  if (!is.numeric(n.sims) || n.sims <= 0) stop("Number of simulations must be a positive number.")
  if (!is.null(mean.scores) && (trials %% mean.scores != 0)) stop("Mean.scores should be a divisor of trials.")
  if (nstart <= 2){
    nstart <- 3
    warning("`nstart` was set to 3, since testing requires a certain amount of variance in the data.")
  }
  if(length(method) > 1) method <- method[1]
  if (method == "files" && !dir.exists(filespath)) stop("Specified filespath does not exist.")
  if (method == "files" && length(list.files(filespath, pattern = "*.txt")) < n.sims) stop("Number of simulations is larger than amount of random files.")
  if (method == "quantis") {
    # test quantis
    system(paste0('EasyQuantis -u 0 -n 1 --min 0 --max 1 -i "tmp.txt"'))
    if ("tmp.txt" %in% list.files()) unlink("tmp.txt")
    else stop("Could not create random bits from QRNG. Is the device connected? Consider using a different method.")
  }
  if (method == "quantis" && parallel) {
    message("Parallel processing is not supported with EasyQuantis. Setting parallel to FALSE.")
    parallel <- FALSE
  }
  if (!method %in% c("pseudo", "files", "quantis")) stop("Method must be either 'pseudo', 'files' or 'quantis'.")

  
  maxbit <- (1 / p) - 1
  
  message("Generating ", n.sims, " simulations...")
  message("Using ", method, " generation and ", ifelse(parallel, "parallel", "sequential"), " processing")
  
  generate_simulation <- function(i) {
    if (method == "files") {
      simf <- read.table(rfiles[i])
      if (trials > nrow(simf)) stop("Number of trials is larger than amount of random bits per file!")
      if (trials < nrow(simf)) {
        line.start <- sample.int(nrow(simf) - trials, 1)
        sim <- data.frame(V1 = simf[line.start:(line.start + trials - 1), ])
      } else {
        sim <- data.frame(V1 = simf)
      }
    } else {
      if (method == "quantis") {
        if ("tmp.txt" %in% list.files()) unlink("tmp.txt")
        system(paste0('EasyQuantis -u 0 -n ', trials, ' --min 0 --max ', maxbit, ' -i "tmp.txt"'), ignore.stdout = T, ignore.stderr = T)
        if ("tmp.txt" %in% list.files()) {
          sim <- read.table("tmp.txt")
        } else stop("Could not create random bits from QRNG. Is the device connected? Consider using use.quantis = FALSE.")
      } else {
        sim <- data.frame(V1 = rbinom(trials, 1, p))
      }
    }
    
    if (!is.null(mean.scores)) {
      sim$group <- rep(1:(nrow(sim) / (mean.scores * (1 / p))), each = mean.scores * (1 / p))
      if (p != 0.5) sim[, 1] <- ifelse(sim[, 1] == 0, 1, 0)
      sim <- tapply(sim[, 1], sim$group, sum)
      
      if (var(sim[1:nstart]) == 0) repeat {
        if (method == "files") {
          line.start <- sample.int(nrow(simf) - trials, 1)
          sim <- data.frame(V1 = simf[line.start:(line.start + trials - 1), ])
          sim$group <- rep(1:(nrow(sim) / (mean.scores * (1 / p))), each = mean.scores * (1 / p))
          sim <- tapply(sim[, 1], sim$group, sum)
        } else if (method == "quantis") {
          system(paste0('EasyQuantis -u 0 -n ', trials, ' --min 0 --max ', maxbit, ' -i "tmp.txt"'), ignore.stdout = T, ignore.stderr = T)
          if ("tmp.txt" %in% list.files()) {
            sim <- read.table("tmp.txt")
          } else stop("Could not create random bits from QRNG. Is the device connected? Consider using use.quantis = FALSE.")
        } else {
          sim <- data.frame(V1 = rbinom(trials, 1, p))
        }
        
        if (var(sim[1:nstart]) != 0) break
      }
      
      sim <- data.frame(sums = sim)
      sim$cumsum <- cumsum(sim$sums - mean.scores)
      sim$bf <- ifelse(parallel,
                       changeofevidence::bfttest(sim$sums, alternative = alternative, mu = mean.scores, prior.loc = prior.loc, prior.r = prior.r, nstart = nstart)$BF,
                       .quiet(changeofevidence::bfttest(sim$sums, alternative = alternative, mu = mean.scores, prior.loc = prior.loc, prior.r = prior.r, nstart = nstart)$BF)
      )
    } else {
      sim$qbitmin1 <- ifelse(sim[, 1] == 0, -1, 1)
      sim$cumsum <- cumsum(sim$qbitmin1)
      sim$bf <- ifelse(parallel,
                       changeofevidence::bfbinom(sim$V1, p = p, prior.r = prior.r, nstart = nstart)$BF,
                       .quiet(changeofevidence::bfbinom(sim$V1, p = p, prior.r = prior.r, nstart = nstart)$BF)
      )
    }
    
    # FFT computations
    L <- length(sim$cumsum)
    Y <- fft(sim$cumsum)
    P <- abs(Y / L)
    Y2 <- fft(sim$bf)
    P2 <- abs(Y2 / L)
    
    index <- 1:L
    data.frame(simid = i, index = index, raw = sim[, 1], rw = sim$cumsum, density.rw = P, bf = sim$bf, density.bf = P2)
  }
  
  rfiles <- if (method == "files") list.files(filespath, full.names = TRUE, pattern = "*.txt") else NULL
  
  if (parallel) {
    cores <- parallel::detectCores() - 1
    cl <- parallel::makeCluster(cores)
    sim.out <- do.call(rbind, pbapply::pblapply(1:n.sims, function(i) {
      generate_simulation(i)
    }, cl = cl))
    parallel::stopCluster(cl)
  } else {
    sim.out <- do.call(rbind, pbapply::pblapply(1:n.sims, function(i) {
      generate_simulation(i)
    }))
  }
  
  return(sim.out)
}

# Helper
.quiet <- function(x) { 
  sink(tempfile()) 
  on.exit(sink()) 
  invisible(force(x)) 
}
